--  ELIMINAMOS EL PACIENTE CON EL DNI '10289289'
DELETE FROM Paciente WHERE DNI='10289289'

--  ELIMINAMOS LOS PACIENTES DE SEXO FEMENINO NACIDOS ANTES DE 1980
DELETE FROM Paciente WHERE Sexo='F' AND FechaNacimiento < '1980-01-01'

--  ELIMINAMOS EL DOCTOR CON EL CMP '017888'
DELETE FROM Doctor WHERE NumeroCMP='017888'

--  ELIMINAMOS LOS DOCTORES CUYA ESPECIALIDAD SEA 'Traumatologo'
DELETE FROM Doctor WHERE Especialidad='Traumatologo'

--  ELIMINAMOS LA HISTORIA CLINICA CON EL NUMERO 'HC0002'
DELETE FROM HistoriaClinica WHERE Numero='HC0002'

--  ELIMINAMOS LAS HISTORIAS CLINICAS QUE NO ESTEN VIGENTES
DELETE FROM HistoriaClinica WHERE Vigente=0


--  ELIMINAMOS LA CITA CON EL NUMERO 1
DELETE FROM Cita WHERE Numero=1

--  ELIMINAMOS LAS CITAS CON COSTO MENOR A 100
DELETE FROM Cita WHERE Costo < 100
